// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listUnlockedAchievements = `-- name: ListUnlockedAchievements :many
SELECT user_id, achievement_id, unlocked_at FROM user_achievements WHERE user_id = $1
`

func (q *Queries) ListUnlockedAchievements(ctx context.Context, userID uuid.UUID) ([]UserAchievement, error) {
	rows, err := q.db.Query(ctx, listUnlockedAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAchievement{}
	for rows.Next() {
		var i UserAchievement
		if err := rows.Scan(&i.UserID, &i.AchievementID, &i.UnlockedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockAchievement = `-- name: UnlockAchievement :one
INSERT INTO user_achievements (user_id, achievement_id)
VALUES ($1, $2)
ON CONFLICT (user_id, achievement_id) DO UPDATE SET achievement_id = user_achievements.achievement_id
RETURNING user_id, achievement_id, unlocked_at
`

type UnlockAchievementParams struct {
	UserID        uuid.UUID `json:"user_id"`
	AchievementID string    `json:"achievement_id"`
}

func (q *Queries) UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) (UserAchievement, error) {
	row := q.db.QueryRow(ctx, unlockAchievement, arg.UserID, arg.AchievementID)
	var i UserAchievement
	err := row.Scan(&i.UserID, &i.AchievementID, &i.UnlockedAt)
	return i, err
}
