// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dialog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserDialogMessagesBySender = `-- name: CountUserDialogMessagesBySender :one
SELECT COUNT(*) FROM dialog_messages dm
JOIN dialog_sessions ds ON ds.id = dm.session_id
WHERE ds.user_id = $1 AND dm.sender = $2
`

type CountUserDialogMessagesBySenderParams struct {
	UserID uuid.UUID `json:"user_id"`
	Sender string    `json:"sender"`
}

func (q *Queries) CountUserDialogMessagesBySender(ctx context.Context, arg CountUserDialogMessagesBySenderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserDialogMessagesBySender, arg.UserID, arg.Sender)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDialogMessage = `-- name: CreateDialogMessage :one
INSERT INTO dialog_messages (session_id, sender, text, cost_diamonds)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, sender, text, cost_diamonds, created_at
`

type CreateDialogMessageParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	Sender       string    `json:"sender"`
	Text         string    `json:"text"`
	CostDiamonds int32     `json:"cost_diamonds"`
}

func (q *Queries) CreateDialogMessage(ctx context.Context, arg CreateDialogMessageParams) (DialogMessage, error) {
	row := q.db.QueryRow(ctx, createDialogMessage,
		arg.SessionID,
		arg.Sender,
		arg.Text,
		arg.CostDiamonds,
	)
	var i DialogMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Sender,
		&i.Text,
		&i.CostDiamonds,
		&i.CreatedAt,
	)
	return i, err
}

const createDialogSession = `-- name: CreateDialogSession :one
INSERT INTO dialog_sessions (user_id, character_id, scene_id, limit_type, limit_value)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, character_id, scene_id, status, limit_type, limit_value, message_count, started_at, ended_at, end_reason
`

type CreateDialogSessionParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	CharacterID uuid.UUID   `json:"character_id"`
	SceneID     uuid.UUID   `json:"scene_id"`
	LimitType   string      `json:"limit_type"`
	LimitValue  pgtype.Int4 `json:"limit_value"`
}

func (q *Queries) CreateDialogSession(ctx context.Context, arg CreateDialogSessionParams) (DialogSession, error) {
	row := q.db.QueryRow(ctx, createDialogSession,
		arg.UserID,
		arg.CharacterID,
		arg.SceneID,
		arg.LimitType,
		arg.LimitValue,
	)
	var i DialogSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CharacterID,
		&i.SceneID,
		&i.Status,
		&i.LimitType,
		&i.LimitValue,
		&i.MessageCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const endDialogSession = `-- name: EndDialogSession :one
UPDATE dialog_sessions
SET status = 'ended',
    ended_at = now(),
    end_reason = $2
WHERE id = $1 AND status = 'active'
RETURNING id, user_id, character_id, scene_id, status, limit_type, limit_value, message_count, started_at, ended_at, end_reason
`

type EndDialogSessionParams struct {
	ID        uuid.UUID   `json:"id"`
	EndReason pgtype.Text `json:"end_reason"`
}

func (q *Queries) EndDialogSession(ctx context.Context, arg EndDialogSessionParams) (DialogSession, error) {
	row := q.db.QueryRow(ctx, endDialogSession, arg.ID, arg.EndReason)
	var i DialogSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CharacterID,
		&i.SceneID,
		&i.Status,
		&i.LimitType,
		&i.LimitValue,
		&i.MessageCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const getDialogSession = `-- name: GetDialogSession :one
SELECT id, user_id, character_id, scene_id, status, limit_type, limit_value, message_count, started_at, ended_at, end_reason FROM dialog_sessions WHERE id = $1
`

func (q *Queries) GetDialogSession(ctx context.Context, id uuid.UUID) (DialogSession, error) {
	row := q.db.QueryRow(ctx, getDialogSession, id)
	var i DialogSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CharacterID,
		&i.SceneID,
		&i.Status,
		&i.LimitType,
		&i.LimitValue,
		&i.MessageCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const getDialogSessionForUpdate = `-- name: GetDialogSessionForUpdate :one
SELECT id, user_id, character_id, scene_id, status, limit_type, limit_value, message_count, started_at, ended_at, end_reason FROM dialog_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetDialogSessionForUpdate(ctx context.Context, id uuid.UUID) (DialogSession, error) {
	row := q.db.QueryRow(ctx, getDialogSessionForUpdate, id)
	var i DialogSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CharacterID,
		&i.SceneID,
		&i.Status,
		&i.LimitType,
		&i.LimitValue,
		&i.MessageCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const incrementDialogSessionMessageCount = `-- name: IncrementDialogSessionMessageCount :one
UPDATE dialog_sessions
SET message_count = message_count + 1
WHERE id = $1
RETURNING id, user_id, character_id, scene_id, status, limit_type, limit_value, message_count, started_at, ended_at, end_reason
`

func (q *Queries) IncrementDialogSessionMessageCount(ctx context.Context, id uuid.UUID) (DialogSession, error) {
	row := q.db.QueryRow(ctx, incrementDialogSessionMessageCount, id)
	var i DialogSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CharacterID,
		&i.SceneID,
		&i.Status,
		&i.LimitType,
		&i.LimitValue,
		&i.MessageCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const listDialogMessages = `-- name: ListDialogMessages :many
SELECT id, session_id, sender, text, cost_diamonds, created_at FROM dialog_messages WHERE session_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListDialogMessages(ctx context.Context, sessionID uuid.UUID) ([]DialogMessage, error) {
	rows, err := q.db.Query(ctx, listDialogMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DialogMessage{}
	for rows.Next() {
		var i DialogMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Sender,
			&i.Text,
			&i.CostDiamonds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredTimeLimitedSessions = `-- name: ListExpiredTimeLimitedSessions :many
SELECT id, user_id, character_id, scene_id, status, limit_type, limit_value, message_count, started_at, ended_at, end_reason FROM dialog_sessions
WHERE status = 'active'
  AND limit_type = 'time'
  AND limit_value IS NOT NULL
  AND started_at + make_interval(secs => limit_value) <= now()
`

func (q *Queries) ListExpiredTimeLimitedSessions(ctx context.Context) ([]DialogSession, error) {
	rows, err := q.db.Query(ctx, listExpiredTimeLimitedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DialogSession{}
	for rows.Next() {
		var i DialogSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CharacterID,
			&i.SceneID,
			&i.Status,
			&i.LimitType,
			&i.LimitValue,
			&i.MessageCount,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
