// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Choice struct {
	ID           uuid.UUID   `json:"id"`
	SceneID      uuid.UUID   `json:"scene_id"`
	Text         string      `json:"text"`
	IsPaid       bool        `json:"is_paid"`
	CostDiamonds int32       `json:"cost_diamonds"`
	NextSceneID  pgtype.UUID `json:"next_scene_id"`
}

type DialogMessage struct {
	ID           uuid.UUID `json:"id"`
	SessionID    uuid.UUID `json:"session_id"`
	Sender       string    `json:"sender"`
	Text         string    `json:"text"`
	CostDiamonds int32     `json:"cost_diamonds"`
	CreatedAt    time.Time `json:"created_at"`
}

type DialogSession struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	CharacterID  uuid.UUID          `json:"character_id"`
	SceneID      uuid.UUID          `json:"scene_id"`
	Status       string             `json:"status"`
	LimitType    string             `json:"limit_type"`
	LimitValue   pgtype.Int4        `json:"limit_value"`
	MessageCount int32              `json:"message_count"`
	StartedAt    time.Time          `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	EndReason    pgtype.Text        `json:"end_reason"`
}

type PlayerProgress struct {
	UserID         uuid.UUID `json:"user_id"`
	StoryID        uuid.UUID `json:"story_id"`
	CurrentSceneID uuid.UUID `json:"current_scene_id"`
	ChoicesMade    []byte    `json:"choices_made"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Scene struct {
	ID                uuid.UUID   `json:"id"`
	StoryID           uuid.UUID   `json:"story_id"`
	OrderIndex        int32       `json:"order_index"`
	BackgroundUrl     pgtype.Text `json:"background_url"`
	CharacterID       pgtype.UUID `json:"character_id"`
	DialogueScript    []byte      `json:"dialogue_script"`
	FreeDialogEnabled bool        `json:"free_dialog_enabled"`
	DialogLimitType   pgtype.Text `json:"dialog_limit_type"`
	DialogLimitValue  pgtype.Int4 `json:"dialog_limit_value"`
	CreatedAt         time.Time   `json:"created_at"`
}

type Story struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	CoverUrl    pgtype.Text `json:"cover_url"`
	IsPublished bool        `json:"is_published"`
	CreatedAt   time.Time   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserProfile struct {
	UserID      uuid.UUID   `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Gender      pgtype.Text `json:"gender"`
	Hobbies     []string    `json:"hobbies"`
	Theme       string      `json:"theme"`
	Language    string      `json:"language"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type WalletTransaction struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Amount    int32     `json:"amount"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
}
