// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_progress.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPlayerProgress = `-- name: CreatePlayerProgress :one
INSERT INTO player_progress (user_id, story_id, current_scene_id)
VALUES ($1, $2, $3)
RETURNING user_id, story_id, current_scene_id, choices_made, updated_at
`

type CreatePlayerProgressParams struct {
	UserID         uuid.UUID `json:"user_id"`
	StoryID        uuid.UUID `json:"story_id"`
	CurrentSceneID uuid.UUID `json:"current_scene_id"`
}

func (q *Queries) CreatePlayerProgress(ctx context.Context, arg CreatePlayerProgressParams) (PlayerProgress, error) {
	row := q.db.QueryRow(ctx, createPlayerProgress, arg.UserID, arg.StoryID, arg.CurrentSceneID)
	var i PlayerProgress
	err := row.Scan(
		&i.UserID,
		&i.StoryID,
		&i.CurrentSceneID,
		&i.ChoicesMade,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerProgress = `-- name: GetPlayerProgress :one
SELECT user_id, story_id, current_scene_id, choices_made, updated_at FROM player_progress WHERE user_id = $1 AND story_id = $2
`

type GetPlayerProgressParams struct {
	UserID  uuid.UUID `json:"user_id"`
	StoryID uuid.UUID `json:"story_id"`
}

func (q *Queries) GetPlayerProgress(ctx context.Context, arg GetPlayerProgressParams) (PlayerProgress, error) {
	row := q.db.QueryRow(ctx, getPlayerProgress, arg.UserID, arg.StoryID)
	var i PlayerProgress
	err := row.Scan(
		&i.UserID,
		&i.StoryID,
		&i.CurrentSceneID,
		&i.ChoicesMade,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerProgress = `-- name: UpdatePlayerProgress :one
UPDATE player_progress
SET current_scene_id = $3,
    choices_made = $4,
    updated_at = now()
WHERE user_id = $1 AND story_id = $2
RETURNING user_id, story_id, current_scene_id, choices_made, updated_at
`

type UpdatePlayerProgressParams struct {
	UserID         uuid.UUID `json:"user_id"`
	StoryID        uuid.UUID `json:"story_id"`
	CurrentSceneID uuid.UUID `json:"current_scene_id"`
	ChoicesMade    []byte    `json:"choices_made"`
}

func (q *Queries) UpdatePlayerProgress(ctx context.Context, arg UpdatePlayerProgressParams) (PlayerProgress, error) {
	row := q.db.QueryRow(ctx, updatePlayerProgress,
		arg.UserID,
		arg.StoryID,
		arg.CurrentSceneID,
		arg.ChoicesMade,
	)
	var i PlayerProgress
	err := row.Scan(
		&i.UserID,
		&i.StoryID,
		&i.CurrentSceneID,
		&i.ChoicesMade,
		&i.UpdatedAt,
	)
	return i, err
}
