// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_progress.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayerProgress = `-- name: CreatePlayerProgress :one
INSERT INTO player_progress (user_id, story_id, current_scene_id)
VALUES ($1, $2, $3)
RETURNING user_id, story_id, current_scene_id, choices_made, updated_at
`

type CreatePlayerProgressParams struct {
	UserID         uuid.UUID `json:"user_id"`
	StoryID        uuid.UUID `json:"story_id"`
	CurrentSceneID uuid.UUID `json:"current_scene_id"`
}

func (q *Queries) CreatePlayerProgress(ctx context.Context, arg CreatePlayerProgressParams) (PlayerProgress, error) {
	row := q.db.QueryRow(ctx, createPlayerProgress, arg.UserID, arg.StoryID, arg.CurrentSceneID)
	var i PlayerProgress
	err := row.Scan(
		&i.UserID,
		&i.StoryID,
		&i.CurrentSceneID,
		&i.ChoicesMade,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerProgress = `-- name: GetPlayerProgress :one
SELECT user_id, story_id, current_scene_id, choices_made, updated_at FROM player_progress WHERE user_id = $1 AND story_id = $2
`

type GetPlayerProgressParams struct {
	UserID  uuid.UUID `json:"user_id"`
	StoryID uuid.UUID `json:"story_id"`
}

func (q *Queries) GetPlayerProgress(ctx context.Context, arg GetPlayerProgressParams) (PlayerProgress, error) {
	row := q.db.QueryRow(ctx, getPlayerProgress, arg.UserID, arg.StoryID)
	var i PlayerProgress
	err := row.Scan(
		&i.UserID,
		&i.StoryID,
		&i.CurrentSceneID,
		&i.ChoicesMade,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayerProgressByUser = `-- name: ListPlayerProgressByUser :many
SELECT
    s.id AS story_id,
    s.title AS story_title,
    s.description AS story_description,
    s.cover_url AS story_cover_url,
    s.genre AS story_genre,
    s.status AS story_status,
    s.created_at AS story_created_at,
    pp.current_scene_id,
    pp.choices_made,
    pp.updated_at,
    sc.order_index AS current_order_index,
    (SELECT COUNT(*) FROM scenes WHERE scenes.story_id = s.id)::int AS total_scenes
FROM player_progress pp
JOIN stories s ON s.id = pp.story_id
JOIN scenes sc ON sc.id = pp.current_scene_id
WHERE pp.user_id = $1
ORDER BY pp.updated_at DESC
`

type ListPlayerProgressByUserRow struct {
	StoryID           uuid.UUID   `json:"story_id"`
	StoryTitle        string      `json:"story_title"`
	StoryDescription  pgtype.Text `json:"story_description"`
	StoryCoverUrl     pgtype.Text `json:"story_cover_url"`
	StoryGenre        string      `json:"story_genre"`
	StoryStatus       string      `json:"story_status"`
	StoryCreatedAt    time.Time   `json:"story_created_at"`
	CurrentSceneID    uuid.UUID   `json:"current_scene_id"`
	ChoicesMade       []byte      `json:"choices_made"`
	UpdatedAt         time.Time   `json:"updated_at"`
	CurrentOrderIndex int32       `json:"current_order_index"`
	TotalScenes       int32       `json:"total_scenes"`
}

func (q *Queries) ListPlayerProgressByUser(ctx context.Context, userID uuid.UUID) ([]ListPlayerProgressByUserRow, error) {
	rows, err := q.db.Query(ctx, listPlayerProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerProgressByUserRow{}
	for rows.Next() {
		var i ListPlayerProgressByUserRow
		if err := rows.Scan(
			&i.StoryID,
			&i.StoryTitle,
			&i.StoryDescription,
			&i.StoryCoverUrl,
			&i.StoryGenre,
			&i.StoryStatus,
			&i.StoryCreatedAt,
			&i.CurrentSceneID,
			&i.ChoicesMade,
			&i.UpdatedAt,
			&i.CurrentOrderIndex,
			&i.TotalScenes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerProgress = `-- name: UpdatePlayerProgress :one
UPDATE player_progress
SET current_scene_id = $3,
    choices_made = $4,
    updated_at = now()
WHERE user_id = $1 AND story_id = $2
RETURNING user_id, story_id, current_scene_id, choices_made, updated_at
`

type UpdatePlayerProgressParams struct {
	UserID         uuid.UUID `json:"user_id"`
	StoryID        uuid.UUID `json:"story_id"`
	CurrentSceneID uuid.UUID `json:"current_scene_id"`
	ChoicesMade    []byte    `json:"choices_made"`
}

func (q *Queries) UpdatePlayerProgress(ctx context.Context, arg UpdatePlayerProgressParams) (PlayerProgress, error) {
	row := q.db.QueryRow(ctx, updatePlayerProgress,
		arg.UserID,
		arg.StoryID,
		arg.CurrentSceneID,
		arg.ChoicesMade,
	)
	var i PlayerProgress
	err := row.Scan(
		&i.UserID,
		&i.StoryID,
		&i.CurrentSceneID,
		&i.ChoicesMade,
		&i.UpdatedAt,
	)
	return i, err
}
