// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scenes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getChoice = `-- name: GetChoice :one
SELECT id, scene_id, text, is_paid, cost_diamonds, next_scene_id FROM choices WHERE id = $1
`

func (q *Queries) GetChoice(ctx context.Context, id uuid.UUID) (Choice, error) {
	row := q.db.QueryRow(ctx, getChoice, id)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.Text,
		&i.IsPaid,
		&i.CostDiamonds,
		&i.NextSceneID,
	)
	return i, err
}

const getScene = `-- name: GetScene :one
SELECT id, story_id, order_index, background_url, character_id, dialogue_script, free_dialog_enabled, dialog_limit_type, dialog_limit_value, created_at FROM scenes WHERE id = $1
`

func (q *Queries) GetScene(ctx context.Context, id uuid.UUID) (Scene, error) {
	row := q.db.QueryRow(ctx, getScene, id)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.OrderIndex,
		&i.BackgroundUrl,
		&i.CharacterID,
		&i.DialogueScript,
		&i.FreeDialogEnabled,
		&i.DialogLimitType,
		&i.DialogLimitValue,
		&i.CreatedAt,
	)
	return i, err
}

const listChoicesByScene = `-- name: ListChoicesByScene :many
SELECT id, scene_id, text, is_paid, cost_diamonds, next_scene_id FROM choices WHERE scene_id = $1 ORDER BY id ASC
`

func (q *Queries) ListChoicesByScene(ctx context.Context, sceneID uuid.UUID) ([]Choice, error) {
	rows, err := q.db.Query(ctx, listChoicesByScene, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Choice{}
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.Text,
			&i.IsPaid,
			&i.CostDiamonds,
			&i.NextSceneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
