// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getFirstSceneOfStory = `-- name: GetFirstSceneOfStory :one
SELECT id, story_id, order_index, background_url, character_id, dialogue_script, free_dialog_enabled, dialog_limit_type, dialog_limit_value, created_at FROM scenes WHERE story_id = $1 ORDER BY order_index ASC LIMIT 1
`

func (q *Queries) GetFirstSceneOfStory(ctx context.Context, storyID uuid.UUID) (Scene, error) {
	row := q.db.QueryRow(ctx, getFirstSceneOfStory, storyID)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.OrderIndex,
		&i.BackgroundUrl,
		&i.CharacterID,
		&i.DialogueScript,
		&i.FreeDialogEnabled,
		&i.DialogLimitType,
		&i.DialogLimitValue,
		&i.CreatedAt,
	)
	return i, err
}

const getStory = `-- name: GetStory :one
SELECT id, title, description, cover_url, is_published, created_at FROM stories WHERE id = $1
`

func (q *Queries) GetStory(ctx context.Context, id uuid.UUID) (Story, error) {
	row := q.db.QueryRow(ctx, getStory, id)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.IsPublished,
		&i.CreatedAt,
	)
	return i, err
}

const listPublishedStories = `-- name: ListPublishedStories :many
SELECT id, title, description, cover_url, is_published, created_at FROM stories WHERE is_published = true ORDER BY created_at DESC
`

func (q *Queries) ListPublishedStories(ctx context.Context) ([]Story, error) {
	rows, err := q.db.Query(ctx, listPublishedStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.IsPublished,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
