// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_stats.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserStats = `-- name: GetUserStats :one
SELECT user_id, total_reading_seconds, day_streak, longest_streak, last_active_date, updated_at FROM user_stats WHERE user_id = $1
`

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (UserStat, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalReadingSeconds,
		&i.DayStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserStatsHeartbeat = `-- name: UpsertUserStatsHeartbeat :one
INSERT INTO user_stats (user_id, total_reading_seconds, day_streak, longest_streak, last_active_date, updated_at)
VALUES ($1, $2, 1, 1, $3, now())
ON CONFLICT (user_id) DO UPDATE SET
    total_reading_seconds = user_stats.total_reading_seconds + EXCLUDED.total_reading_seconds,
    day_streak = CASE
        WHEN user_stats.last_active_date = EXCLUDED.last_active_date THEN user_stats.day_streak
        WHEN user_stats.last_active_date = EXCLUDED.last_active_date - 1 THEN user_stats.day_streak + 1
        ELSE 1
    END,
    longest_streak = GREATEST(
        user_stats.longest_streak,
        CASE
            WHEN user_stats.last_active_date = EXCLUDED.last_active_date THEN user_stats.day_streak
            WHEN user_stats.last_active_date = EXCLUDED.last_active_date - 1 THEN user_stats.day_streak + 1
            ELSE 1
        END
    ),
    last_active_date = EXCLUDED.last_active_date,
    updated_at = now()
RETURNING user_id, total_reading_seconds, day_streak, longest_streak, last_active_date, updated_at
`

type UpsertUserStatsHeartbeatParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Seconds int64       `json:"seconds"`
	Today   pgtype.Date `json:"today"`
}

func (q *Queries) UpsertUserStatsHeartbeat(ctx context.Context, arg UpsertUserStatsHeartbeatParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, upsertUserStatsHeartbeat, arg.UserID, arg.Seconds, arg.Today)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalReadingSeconds,
		&i.DayStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.UpdatedAt,
	)
	return i, err
}
