// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO wallet_transactions (user_id, amount, reason)
VALUES ($1, $2, $3)
RETURNING id, user_id, amount, reason, created_at
`

type CreateWalletTransactionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Amount int32     `json:"amount"`
	Reason string    `json:"reason"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction, arg.UserID, arg.Amount, arg.Reason)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalDiamondsSpent = `-- name: GetTotalDiamondsSpent :one
SELECT COALESCE(-SUM(amount), 0)::bigint AS total_spent
FROM wallet_transactions
WHERE user_id = $1 AND amount < 0
`

func (q *Queries) GetTotalDiamondsSpent(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalDiamondsSpent, userID)
	var total_spent int64
	err := row.Scan(&total_spent)
	return total_spent, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT COALESCE(SUM(amount), 0)::bigint AS balance
FROM wallet_transactions
WHERE user_id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletBalance, userID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const lockWallet = `-- name: LockWallet :exec
SELECT pg_advisory_xact_lock(hashtext($1::text))
`

// Advisory transaction-scoped lock keyed by user id. wallet_transactions has
// no balance row to lock with SELECT ... FOR UPDATE, and locking existing
// rows wouldn't block a concurrent INSERT anyway, so we serialize
// read-balance-then-insert per user with an advisory lock instead.
func (q *Queries) LockWallet(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, lockWallet, userID)
	return err
}
